<?php

/**
 * @file
 * Contains update functions for Custom add another.
 */

/**
 * Implements hook_update_last_removed().
 */
function custom_add_another_update_last_removed() {
  return 7101;
}

/**
 * Implements hook_update_N().
 */
function custom_add_another_update_1000() {
  $config = config('custom_add_another.settings');
}

/**
 * Implements hook_install().
 */
function custom_add_another_install() {
  // Dynamically generated variable data was detected.
}

