<?php

/**
 * @file
 *   Allows the 'Add another item' button text to be customised.
 */

/**
 * Implements hook_field_info_alter().
 */
function custom_add_another_field_info_alter(&$info) {
  // Add the 'custom_add_another' instance setting to all field types.
  foreach ($info as $field_type => &$field_type_info) {
    $field_type_info += array('instance_settings' => array());
    $field_type_info['instance_settings'] += array(
      'custom_add_another' => '',
    );
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a checkbox for the 'custom_add_another' instance settings on the 'Edit
 * field instance' form.
 */
function custom_add_another_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  $instance = $form['#instance'];

  $form['instance']['settings']['custom_add_another'] = array(
    '#type' => 'textfield',
    '#title' => t('Custom add another item button'),
    '#description' => t("If the number of items in this field is set to 'Unlimited' then you might get a button that allows you to 'Add another item'. You may customise the text for that button here, an empty value will just use the default value for the button text."),
    // Add a hint for the empty value if hint module is around.
    '#hint' => t('Add another item'),
    '#default_value' => $instance['settings']['custom_add_another'],

    // Hidden when the 'Number of values' is not unlimited.
    '#states' => array(
      'visible' => array(
        ':input[name="field[cardinality]"]' => array('value' => (string)FIELD_CARDINALITY_UNLIMITED),
      ),
    ),
  );
}

/**
 * Implements hook_field_attach_form().
 *
 * Change the 'Add another item' button for the fields that have a
 * customisation.
 */
function custom_add_another_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  foreach ($form_state['field'] as $field_name => $field) {
    if (isset($field[$langcode])) {
      $cardinality = $field[$langcode]['field']['cardinality'];
      $instance_settings = $field[$langcode]['instance']['settings'];
      if (($cardinality == FIELD_CARDINALITY_UNLIMITED) && !empty($instance_settings['custom_add_another'])) {
        // Go find and set the add another button in the form.
        if (isset($form[$field_name][$langcode]['add_more']) && ($form[$field_name][$langcode]['add_more']['#type'] == 'submit')) {
          // @TODO: workout how to translate this value.
          $form[$field_name][$langcode]['add_more']['#value'] = $instance_settings['custom_add_another'];
        }
      }
    }
  }
}
